import { useEffect, useRef, useState, type CSSProperties } from 'react';
import PixelTwin from './PixelTwin';
import { useI18n } from '../i18n';
import type { Gender } from '../useAuth';
import { BookOpen } from 'lucide-react';
type Area = 'home' | 'profile' | 'today' | 'discover' | 'twin';
export default function KitchenRoom({ open, busy, selection, vitality, onOpen, gender, birthYear, birthMonth, avatarRef, onOpenNotebook, notebookRef }: { open: boolean; busy: boolean; selection: boolean; vitality: string; onOpen: (area: Area) => void; gender: Gender; birthYear: number | null; birthMonth: number | null; avatarRef: React.RefObject<HTMLButtonElement | null>; onOpenNotebook: () => void; notebookRef: React.RefObject<HTMLButtonElement | null> }) {
    const { t } = useI18n(); const room = useRef<HTMLDivElement>(null); const camera = useRef<HTMLDivElement>(null); const drag = useRef({ x: 0, y: 0, left: 0, top: 0, active: false, moved: false }); const [offset, setOffset] = useState({ x: 0, y: 0 }); const [position, setPosition] = useState({ x: 50, y: 74 }); const [walking, setWalking] = useState(false); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
    const [notebookVisible, setNotebookVisible] = useState(false);
    function move(x: number, y: number) { if (open || busy) return; const nextY = Math.max(64, Math.min(90, y)); const nextX = Math.max(nextY >= 76 ? 36 : 12, Math.min(nextY >= 76 ? 68 : 88, x)); setPosition({ x: nextX, y: nextY }); setWalking(true); if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => setWalking(false), 650); }
    useEffect(() => () => { if (timer.current) clearTimeout(timer.current); }, []);
    useEffect(() => { const el = camera.current; if (el && window.matchMedia('(max-width:700px)').matches) { el.scrollLeft = (900 - el.clientWidth) / 2; el.scrollTop = Math.max(0, 800 - el.clientHeight); } }, []);
    function interact(area: Area, x: number, y: number) { setNotebookVisible(false); move(x, y); onOpen(area); }
    return <div className={`room-camera ${open ? 'room-camera--locked' : ''}`} ref={camera} onScroll={e => setOffset({ x: e.currentTarget.scrollLeft, y: e.currentTarget.scrollTop })} onPointerDown={e => { if (open || e.pointerType !== 'mouse' || !window.matchMedia('(max-width:700px)').matches) return; drag.current = { x: e.clientX, y: e.clientY, left: e.currentTarget.scrollLeft, top: e.currentTarget.scrollTop, active: true, moved: false }; }} onPointerMove={e => { const d = drag.current; if (!d.active) return; const dx = e.clientX - d.x, dy = e.clientY - d.y; if (Math.abs(dx) + Math.abs(dy) > 6) { d.moved = true; e.currentTarget.setPointerCapture(e.pointerId); e.currentTarget.scrollLeft = d.left - dx; e.currentTarget.scrollTop = d.top - dy; } }} onPointerUp={() => { drag.current.active = false; }} onPointerCancel={() => { drag.current.active = false; }} onClickCapture={e => { if (drag.current.moved) { e.preventDefault(); e.stopPropagation(); drag.current.moved = false; } }} style={{ '--dialog-avatar-x': `${offset.x + (camera.current?.clientWidth || 375) / 2}px`, '--dialog-avatar-y': `${offset.y + (camera.current?.clientHeight || 812) * .44}px` } as CSSProperties}><div ref={room} className={`play-room ${open ? 'play-room--open' : ''}`} role="region" aria-label={t('farmScene')} tabIndex={0} onKeyDown={e => { if (open || busy) return; const shifts: Record<string, [number, number]> = { ArrowLeft: [-3, 0], ArrowRight: [3, 0], ArrowUp: [0, -3], ArrowDown: [0, 3], a: [-3, 0], d: [3, 0], w: [0, -3], s: [0, 3] }; const delta = shifts[e.key]; if (delta) { e.preventDefault(); move(position.x + delta[0], position.y + delta[1]); } }}>
        <div className="room-wall" aria-hidden="true" /><div className="room-floor" aria-hidden="true" /><div className="room-skirt" aria-hidden="true" />
        <div className="room-cabinets" aria-hidden="true"><i /><i /><i /></div><div className="room-counter" aria-hidden="true"><div className="room-stove"><i /><i /></div><div className="room-sink" /><div className="room-cup" /></div>
        <div className="room-daylight" aria-hidden="true"><i /><span /></div><div className="room-pot" aria-hidden="true"><i /><i /><i /></div><div className="room-rug" aria-hidden="true" />
        <button className="furniture furniture-fridge" aria-label={t('collection.personalTastes')} disabled={open || busy} onClick={() => interact('profile', 22, 67)}><span className="fridge-freezer" /><span className="fridge-leaf" /><span className="object-caption">{t('collection.personalTastes')}</span></button>
        <button className="furniture furniture-table" aria-label={t('todayTitle')} disabled={open || busy} onClick={() => interact('today', 34, 77)}><span className="table-top"><span className="room-plate"><i /></span><span className="room-fork" /><span className="table-glass" /></span><span className="table-leg leg-one" /><span className="table-leg leg-two" /><span className="object-caption">{t('todayTitle')}</span></button>
        <button className="furniture furniture-map" aria-label={t('discoverTitle')} disabled={open || busy} onClick={() => interact('discover', 75, 64)}><span className="map-paper"><i /><span className="map-pin" /></span><span className="object-caption">{t('discoverTitle')}</span></button>
        <button className="furniture furniture-journal" aria-label={t('twinTitle')} disabled={open || busy} onClick={() => interact('twin', 76, 79)}><span className="journal-shelf" /><span className="journal-book"><i>♥</i></span><span className="object-caption">{t('twinTitle')}</span></button>
        <div className="walk-floor" aria-hidden="true" onClick={e => { const b = room.current!.getBoundingClientRect(); move((e.clientX - b.left) / b.width * 100, (e.clientY - b.top) / b.height * 100); room.current?.focus(); }} />
        <button ref={avatarRef} type="button" className={`room-avatar ${walking ? 'room-avatar--walking' : ''}`} style={{ left: `${position.x}%`, top: `${position.y}%` }} disabled={open || busy} aria-label={t('accountTitle')} title={t('collection.notebook')} aria-expanded={notebookVisible} aria-controls="room-notebook" onPointerDown={event => event.stopPropagation()} onKeyDown={event => { if (event.key === 'Escape') setNotebookVisible(false); event.stopPropagation(); }} onClick={() => setNotebookVisible(previous => !previous)}><span className="avatar-hearts" aria-label={t('wellbeing.' + vitality)}>{vitality === 'balanced' ? '♥ ♥ ♥' : vitality === 'growing' ? '♥ ♥ ♡' : vitality === 'low' ? '♥ ♡ ♡' : '♡ ♡ ♡'}</span><PixelTwin gender={gender} birthYear={birthYear} birthMonth={birthMonth} state={busy ? 'thinking' : selection || vitality === 'balanced' ? 'happy' : 'idle'} /></button>
        <span className="room-control-hint">{t('roomControls')}</span>
        {notebookVisible && <button ref={notebookRef} id="room-notebook" type="button" className="room-notebook" aria-label={t('collection.notebook')} title={t('collection.notebook')} disabled={open || busy} style={{ left: `${position.x}%`, top: `${position.y}%` }} onPointerDown={event => event.stopPropagation()} onKeyDown={event => event.stopPropagation()} onClick={onOpenNotebook}><BookOpen size={22} /></button>}
    </div><span className="camera-pan-hint">{t('panRoom')}</span></div>;
}
